name: Auto-Merge Community PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Approve pull request
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve
