name: Auto-Merge Approved PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Count +1 reactions
        id: count-reactions
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reactions } = await github.rest.reactions.listForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });
            const upvotes = reactions.filter(r => r.content === '+1').length;
            core.setOutput('vote_count', upvotes);
            
      - name: Merge PR if approved
        if: steps.count-reactions.outputs.vote_count >= 1
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.AUTO_MERGE_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
