name: Auto-Merge Community PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  process-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Votes
        id: verify
        uses: actions/github-script@v6
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
        with:
          script: |
            const { data: reactions } = await github.rest.reactions.listForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });
            const votes = reactions.filter(r => r.content === '+1').length;
            core.setOutput('approved', votes >= 1);
            console.log(`Votos: ${votes}/1`);

      - name: Merge PR
        if: steps.verify.outputs.approved == 'true'
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.AUTO_MERGE_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge" \
            -d '{"merge_method":"merge"}'
