name: Auto-Merge Community PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Approve PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { pull_request } = context.payload;
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_request.number,
            const hasApproval = reviews.some(review => review.state === 'APPROVED');
            if (!hasApproval) {
              throw new Error('PR does not have required approvals');
            } else {
              console.log('PR has required approvals');
            }
