name: Auto-Merge Community Approved PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  process-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Count +1 Reactions
        id: count-votes
        uses: actions/github-script@v6
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
        with:
          script: |
            const { data: reactions } = await github.rest.reactions.listForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });
            const upvotes = reactions.filter(r => r.content === '+1').length;
            core.setOutput('total_votes', upvotes);
            console.log(`Votos recebidos: ${upvotes}`);

      - name: Merge Approved PR
        if: steps.count-votes.outputs.total_votes >= 1
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
          MERGE_METHOD: 'merge'
          PRESET: 'DEPENDABOT_MINOR'
